apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userbackend.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: userbackend
  template:
    metadata:
     labels:
        app: userbackend
    spec:
      containers:
        - name: userbackend
          image: "{{ .Values.image.repository }}"
          command: [ "sleep" ]
          args: [ "infinity" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"